a. O valor de v_customer no bloco aninhado é: 201 NUMBER(7)
b. O valor de v_name no bloco aninhado é: 'Unisport' VARCHAR2(25)
c. O valor de v_credit_rating no bloco aninhado é: 'GOOD' VARCHAR2(50)
d. O valor de v_customer no bloco principal é: 'Womansport' VARCHAR2(50)
e. O valor de v_name no bloco principal é: Não é declarado
f. O valor de v_credit_rating no bloco principal é: 'EXCELLENT' VARCHAR2(50)